### ISSUE TITLE
Use futures-rs for async polling

### ISSUE THREAD

**Issue by oberien** [Ediacarium/walkie-talkie-pi#2]
Currently the approach in this repository with asynchronous reads is to create a new threads locking synchronously on reads, then sending the results through senders. This can be improved to a single-threaded async program.

**Comment by Ediacarium** [comment]
First of all this project is far from finished. This isn't just the packet layer. 
The RPi 3 has multiple small cores, meaning having all the load on a single core isn't the best idea.
In Addition will the RPi have to do the Audio-Recording and Playback, meaning it will have to decode
and encode on the fly, which will, as i predict take up quite a lot of CPUtime, meaning i need another thread anyway.

If this was a program for your PC at home I'd say you're right, as opening more threads is usually not a good idea. 
Therefore i am closing this, but i am keeping this in mind will i ever have to many threads on my hand :)
